apiVersion: autoscaling.karmada.io/v1alpha1
kind: CronFederatedHPA
metadata:
  name: nginx-cronfhpa
  namespace: default
spec:
   scaleTargetRef:
      apiVersion: autoscaling.karmada.io/v1alpha1
      kind: FederatedHPA
      name: nginx-fhpa
   rules:
   - name: "scale-up"
     schedule: "0-58/2 * * * *"
     targetMinReplicas: 7
   - name: "scale-down"
     schedule: "1-59/2 * * * *"
     targetMinReplicas: 3