apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-weight-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  placement:
    clusterTolerations:
      - effect: NoExecute
        key: workload-rebalancer-test
        operator: Exists
        tolerationSeconds: 0
    clusterAffinity:
      clusterNames:
        - gke-member-01
        - gke-member-03
    replicaScheduling:
      replicaSchedulingType: Divided
      replicaDivisionPreference: Weighted
      weightPreference:
        # dynamicWeight: AvailableReplicas
        staticWeightList:
          - targetCluster:
              clusterNames:
                - gke-member-01
            weight: 1
          - targetCluster:
              clusterNames:
                - gke-member-03
            weight: 1